name = "pipe-worker"
main = "./src/index.ts"
compatibility_date = "2024-05-14"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "pipe-db"
database_id = "47e15701-3f83-492a-baed-f0add67f549d"
